apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: meportal
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJtZXBvcnRhbDk1Lmpmcm9nLmlvIjogewoJCQkiYXV0aCI6ICJhbVp5YjJjdFpHOWphMlZ5WTNKbFpEcE9ZVzVrZFd4cFptVXhOVE09IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
